### ISSUE TITLE
kindly tell where is the chessboard folder?

### ISSUE THREAD

**Issue by haiderasad** [phuntshoWangdi/Chess-piece-movement-tracker#1]

**Comment by haiderasad** [comment]
can you kindly help with the implementation of this code, i am getting error

**Comment by phuntshoWangdi** [comment]
Ah I forgot to upload chessboard folder and the files. its done now. I have also updated path_loader.py file so that it points to correct file path. I have also added two more files which were missing, predicter.m & final_model.onnx in root folder.
